config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root 'categories#index', as: :authenticated_root
    end
    unauthenticated do
      root 'splashes#index', as: :unauthenticated_root
    end
    get '/users/sign_out' => 'devise/sessions#destroy'
  resources :users
  end
  resources :categories, only: %i[index show edit new create update destroy ] do
    resources :records, only: %i[index show new create update destroy]
  end
end

app/models/splash.rb
class Splash < ApplicationRecord
end

app/controllers/splashes_controller.rb
class SplashesController < ApplicationController
  before_action :set_splash, only: %i[show edit update destroy]

  # GET /splashes or /splashes.json
  def index
    @splashes = Splash.all
  end

  # GET /splashes/1 or /splashes/1.json
  def show; end

  # GET /splashes/new
  def new
    @splash = Splash.new
  end

  # GET /splashes/1/edit
  def edit; end

  # POST /splashes or /splashes.json
  def create
    @splash = Splash.new(splash_params)

    respond_to do |format|
      if @splash.save
        format.html { redirect_to splash_url(@splash), notice: 'Splash was successfully created.' }
        format.json { render :show, status: :created, location: @splash }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @splash.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /splashes/1 or /splashes/1.json
  def update
    respond_to do |format|
      if @splash.update(splash_params)
        format.html { redirect_to splash_url(@splash), notice: 'Splash was successfully updated.' }
        format.json { render :show, status: :ok, location: @splash }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @splash.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /splashes/1 or /splashes/1.json
  def destroy
    @splash.destroy

    respond_to do |format|
      format.html { redirect_to splashes_url, notice: 'Splash was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_splash
    @splash = Splash.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def splash_params
    params.fetch(:splash, {})
  end
end

app/helpers/splashes_helper.rb
module SplashesHelper
end

app/views/splashes/_form.html.erb
<%= form_with(model: splash) do |form| %>
  <% if splash.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(splash.errors.count, "error") %> prohibited this splash from being saved:</h2>

      <ul>
        <% splash.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/splashes/_splash.html.erb
<div id="<%= dom_id splash %>">
</div>

app/views/splashes/edit.html.erb
<h1>Editing splash</h1>

<%= render "form", splash: @splash %>

<br>

<div>
  <%= link_to "Show this splash", @splash %> |
  <%= link_to "Back to splashes", splashes_path %>
</div>

app/views/splashes/index.html.erb
<div class="splash-page d-flex">
  <div class="home-header-categories header">
    <h1> Budget App</h1>
  </div>
  <div class="buttons">
    <%= button_to "Login", new_user_session_path, :method => :get, class:"splash-btns" %>
    <%= button_to "Sign up", new_user_registration_path, :method => :get, class:"splash-btns splash-signup" %>
  </div>
</div>

app/views/splashes/new.html.erb
<h1>New splash</h1>

<%= render "form", splash: @splash %>

<br>

<div>
  <%= link_to "Back to splashes", splashes_path %>
</div>

app/views/splashes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @splash %>

<div>
  <%= link_to "Edit this splash", edit_splash_path(@splash) %> |
  <%= link_to "Back to splashes", splashes_path %>

  <%= button_to "Destroy this splash", @splash, method: :delete %>
</div>